= foot Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:foot: https://codeberg.org/dnkl/foot[foot]
:foot.ini: https://codeberg.org/dnkl/foot/src/branch/master/foot.ini[foot.ini]
:just: https://github.com/casey/just[just]

My configuration for {foot}, the fast, lightweight and minimalist Wayland terminal emulator.

== Usage

This repository contains the configuration file for {foot}.
The reference {foot.ini} file is available in the foot repository.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/foot-config.git
----

. Change to the project's directory.
+
[,sh]
----
cd foot-config
----

. Run `just` to install the config.
+
[,sh]
----
just
----

== Tips and Tricks

=== SSH

When using foot to SSH into another machine, the remote machine needs to have the `foot-terminfo` package installed.
Without this package, things won't behave as expected.
To install it on an `rpm-ostree` system, follow the steps below.

. Install the `foot-terminfo` package.
+
[,sh]
----
sudo rpm-ostree install foot-terminfo
----

. Reboot to apply the changes.
+
[,sh]
----
sudo systemctl reboot
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2022-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
