= foot Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:foot: https://gitlab.com/dnkl/foot[foot]

My configuration for {foot}, the fast, lightweight and minimalist Wayland terminal emulator.

== Usage

This repository contains the configuration file for {Git}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/foot-config.git
----

. Create the _~/.config/foot/_ directory.
+
[source,sh]
----
mkdir ~/.config/foot/
----

. Copy the `foot.ini` file to the config directory.
+
[source,sh]
----
cp ~/Projects/foot-config/foot.ini ~/.config/foot/
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/foot-config.git
----

. Copy the `config` file from the config directory to this repository.
+
[source,sh]
----
cp ~/.config/foot/foot.ini ~/Projects/foot-config/
----

. Stage the updated file.
+
[source,sh]
----
git -C ~/Projects/foot-config add -A
----

. Commit.
+
[source,sh]
----
git -C ~/Projects/foot-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[source,sh]
----
git -C ~/Projects/foot-config push
----

// todo Add instructions for using a merge tool to merge disparate settings files.

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2022 Jordan Williams

== Authors

mailto:{email}[{author}]
